version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 5
  reviewers:
  - aef-
- package-ecosystem: cargo
  directory: "/native/exjack"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 5
