[package]
name = "ex_jack"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "ex_jack"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
jack = "0.11"
futures = { version= "0.3.2", features = ["compat"]}
